on: push

name: Check
env:
  AWS_REGION: "us-east-1"
jobs:
  check:
    name: first-job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
          

    - name: create-ecr-repo
      run: |
        aws ecr create-repository --repository-name hello-world1 --image-scanning-configuration scanOnPush=true --region us-east-1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: https://${{ steps.create-ecr-repo.outputs.registryId }}.dkr.ecr.us-west-2.amazonaws.com
        ECR_REPOSITORY: ${{ steps.create-ecr-repo.outputs.repositoryName}}
        IMAGE_TAG: 1.2
      run: |
        docker build --tag docker-flask-image:$IMAGE_TAG .
        docker images