on: push

name: Check
env:
  ECR_REGISTRY: my-ecr-registry
  ECR_REPOSITORY: my-ecr-repository
  AWS_REGION: us-east-1
  
jobs:
  check:
    name: first-job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
          

    - name: create-ecr-repo
      run: |
        aws ecr create-repository --repository-name hello-world --image-scanning-configuration scanOnPush=true --region us-east-1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.create-ecr-repo.outputs.registry }}
        ECR_REPOSITORY: ${{ steps.create-ecr-repo.outputs.repositoryName}}
        IMAGE_TAG: 1.2
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG